### ISSUE TITLE
请问hard_negative_ctxs是如何得到的，我没有在原始数据中找到正样本的参考文献

### ISSUE THREAD

**Issue by qianlanzz** [zfjsail/OAG-AQA#3]

**Comment by zfjsail** [comment]
``hard_negative_ctxs`` are randomly sampled from the references of positive samples.  References are sampled from [[DBLP Citation Dataset]](https://open.aminer.cn/open/article?id=655db2202ab17a072284bc0c).

**Comment by zfjsail** [comment]
This issue was closed because it has been inactive for 7 days. If there are any other questions, please open a new issue.
